on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  keymap-image:
    name: Generate keymap image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Userspace
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade keymap-drawer
          sudo apt install -y inkscape gsfonts gsfonts-other

      - name: Render images
        run: |
          keymap -c .github/keymap_config.yaml parse -z ./config/splitkb_aurora_sofle.keymap -o keymap.yaml
          keymap -c .github/keymap_config.yaml draw -o keymap.svg keymap.yaml
          inkscape --export-background-opacity=0  ./keymap.svg -o keymap.png

      - name: Upload images
        uses: actions/upload-artifact@v4
        if: always() && !cancelled()
        continue-on-error: true
        with:
          name: keymap
          path: |
            keymap.svg
            keymap.png

  publish:
    name: Publish
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    needs: [build, keymap-image]

    steps:
      - name: Download binaries
        if: always() && !cancelled()
        uses: actions/download-artifact@v4

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        if: always() && !cancelled()
        with:
          token: ${{ github.token }}
          name: Latest ZMK Firmware
          tag_name: 'latest'
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
          files: |
            **/*.hex
            **/*.bin
            **/*.uf2
            **/*.svg
            **/*.png
